extends RefCounted
## User-visible strings are centralized here so later localization can replace
## the storage mechanism without rewriting scene scripts.

const APP_TITLE: String = "1900年：社会与战争"
const APP_SUBTITLE: String = "二维社会与战争模拟 Demo"
const MILESTONE_LABEL: String = "P0-R1 · 玩家闭环补全中"
const MENU_NEW_GAME: String = "新游戏"
const MENU_LOAD_GAME: String = "加载游戏"
const MENU_SETTINGS: String = "设置"
const MENU_QUIT: String = "退出"
const FUTURE_FEATURE_TOOLTIP: String = "此功能将在后续里程碑开放"
const FOOTER: String = "离线单机 · Compatibility 渲染器"
const CLOCK_TITLE: String = "权威游戏时间"
const CLOCK_DESCRIPTION: String = "模拟只按完整游戏小时推进，与渲染帧率无关"
const CLOCK_PAUSE: String = "暂停"
const CLOCK_RESUME: String = "继续"
const CLOCK_STEP: String = "单步 +1 小时"
const CLOCK_BACK: String = "返回主菜单"
const CLOCK_STATUS_PAUSED: String = "已暂停 · 当前速度 %d×"
const CLOCK_STATUS_RUNNING: String = "运行中 · 当前速度 %d×"
const CLOCK_EVENT_COUNT: String = "已结算小时事件：%d"
const CLOCK_CONFIG_ERROR: String = "时间配置加载失败"
const MAP_TITLE: String = "架空世界战略地图"
const MAP_BACK: String = "返回主菜单"
const MAP_CHARACTER: String = "人物信息"
const MAP_ACTION: String = "长期行动"
const MAP_SOCIETY: String = "社会系统"
const MAP_SAVE: String = "保存游戏"
const MAP_HELP: String = "左键选择或拖动 · 滚轮缩放 · 顶部“长期行动”进入玩法"
const MAP_LOAD_ERROR: String = "世界地图加载失败"
const MAP_STAGE_STABLE: String = "稳定控制"
const MAP_STAGE_WEAKENING: String = "控制减弱"
const MAP_STAGE_CONTESTED: String = "争夺中"
const MAP_STAGE_OCCUPIED: String = "敌方占领"
const MAP_STAGE_CONSOLIDATING: String = "控制巩固"
const MAP_RAIL_OPERATIONAL: String = "通行"
const MAP_RAIL_DISRUPTED: String = "中断"
