#!/usr/bin/env python3
"""Run the Batch 2 generator twice and compare all deterministic outputs."""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
GENERATOR = ROOT / "tools" / "historical_data" / "build_1900_source_pack_batch2.py"
COMMITTED = ROOT / "data" / "staging" / "1900"
OUTPUTS = [
    "political_unit_records_1900.json",
    "batch2_manifest.json",
    "batch2_deterministic_corpus.json",
]


def run_generator(directory: Path) -> None:
    completed = subprocess.run(
        [sys.executable, str(GENERATOR), "--output-dir", str(directory)],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if completed.returncode != 0:
        raise RuntimeError(f"generator failed: {completed.stdout}\n{completed.stderr}")


def main() -> int:
    with tempfile.TemporaryDirectory(prefix="wwo-1900-batch2-a-") as first_name, tempfile.TemporaryDirectory(prefix="wwo-1900-batch2-b-") as second_name:
        first = Path(first_name)
        second = Path(second_name)
        run_generator(first)
        run_generator(second)
        for name in OUTPUTS:
            first_bytes = (first / name).read_bytes()
            second_bytes = (second / name).read_bytes()
            committed_bytes = (COMMITTED / name).read_bytes()
            if first_bytes != second_bytes:
                raise RuntimeError(f"non-deterministic generated bytes: {name}")
            if first_bytes != committed_bytes:
                raise RuntimeError(f"committed output differs from clean generation: {name}")

    corpus = json.loads((COMMITTED / "batch2_deterministic_corpus.json").read_text(encoding="utf-8"))
    print(json.dumps({"ok": True, "outputs_compared": OUTPUTS, "expected_records_sha256": corpus["expected_records_sha256"]}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
